# Register user
POST http://localhost:3000/sign-up
Content-Type: application/json

{
    "name": "Marcelo Francisco",
    "email": "marcelofj@gmail.com",
    "password": "12345678",
    "phones": 
    [
        {
            "number": "994902925",
            "ddd": "11"
        },
        {
            "number": "25382263",
            "ddd": "11"
        }
    ]
}

# Authenticate user
###
POST http://localhost:3000/sign-in
Content-Type: application/json

{
    "email": "marcelofj@gmail.com",
    "password": "12345678"
}

# Delete user
###
GET http://localhost:3000/search-user/6144c5ff8b25c8dd6964e43c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDRjNWZmOGIyNWM4ZGQ2OTY0ZTQzYyIsImlhdCI6MTYzMTg5NzA4NywiZXhwIjoxNjMxODk4ODg3fQ.AE0llumbuof9tlhfKpfevsEhnKwsmjc9tVggRQ8P_BY